name: run on released
on:
  release:
    types: [released]
jobs:
  ran-on-released:
    runs-on: ubuntu-latest
    steps:
      - name: triggered from new release
        run: |
          echo "${{ github.ref }} - ${{ github.event_name }} - ${{ toJSON(github.event) }}"
